# Copyright (c) 1999 Matthias Clasen
# See the file COPYING for copying permission.

# Spcat message definitions

I1+PHelp++Print the effective system id for the public id %1.
I1+SHelp++Print the effective system id for system id %1.
I1+pHelp++Print the effective system id for parameter entity %1.
I1+dHelp++Print the effective system id for the doctype %1.
I1+lHelp++Print the effective system id for the linktype %1.
I1+eHelp++Print the effective system id for entity %1.
I1+nHelp++Print the effective system id for notation %1.
I1+sHelp++Print the effective system id for the SGML declaration for doctype %1.
+literal++LITERAL
+name++NAME
