# Copyright (c) 1995 James Clark
# See the file COPYING for copying permission.

# Spam message definitions

E1+invalidMarkupArgument++invalid argument for -m option
E0+tagInSpecialMarkedSection++omitted start or end tag implied in CDATA or RCDATA marked section; not normalized
I1+hHelp++Hoist omitted tags.
I1+lHelp++Prefer lowercase.
I1+mHelp++Use markup option %1.
I1+oHelp++Output the entity named %1.
I1+pHelp++Output the prolog.
I1+rHelp++Raw.
I1+xHelp++Expand references.
+option++OPTION
+name++NAME
