PROG=osx
OBJS=sx.o XmlOutputEventHandler.o sx_inst.o
INCLUDE=
XLIBS=../lib/libosp.a
GENSRCS=XmlOutputMessages.h SxMessages.h sx_inst.cxx

sx.o: SxMessages.h
XmlOutputEventHandler.o: XmlOutputMessages.h
