# Copyright (c) 1994, 1995 James Clark
# See the file COPYING for copying permission.

# nsgmls message definitions

E1+unknownOutputOption++unknown output option %1
I1+BHelp++Enable batch mode.
I1+oHelp++Produce output according to %1.
I1+pHelp++Stop after the document prolog.
I1+sHelp++Suppress output.
I1+tHelp++Send RAST output to file %1.
I1+dHelp++Same as -wduplicate.
I1+lHelp++Same as -oline.
I1+mHelp++Same as -c.
I1+rHelp++Same as -wdefault.
I1+uHelp++Same as -wundef.
+file++FILE
+option++OPTION
