LIB=spgrove
INCLUDE=-I$(srcdir)/../grove
DEPLIBS=-lm -L$(TOP)/grove/.libs -lgrove -L$(TOP)/lib/.libs -lsp $(LIB_THREADS)
OBJS=GroveApp.o GroveBuilder.o SdNode.o
GENSRCS=grove_inst.cxx

GroveBuilder.o: grove_inst.cxx
GroveBuilder.lo: grove_inst.cxx

