#!/bin/sh

set -e

case "$1" in 
    configure)
	# install sp sgml catalog entries
	install-sgmlcatalog --install /etc/sp.catalog sp

	# install doc-base stuff
	if command -v install-docs >/dev/null 2>&1; then
	    echo -n "Registering sp documentation..."
	    install-docs -i /usr/share/doc-base/sp
	    echo "done."
	    # remove legacy package
	    install-docs -r jade-sp >/dev/null 2>&1 || true
	fi
	
    ;;
    
esac

#DEBHELPER#

exit 0
