LIB=style
OBJS=Collector.o \
  DssslSpecEventHandler.o \
  ELObj.o \
  ELObjMessageArg.o \
  Expression.o \
  FOTBuilder.o \
  FlowObj.o \
  InheritedC.o \
  Insn.o \
  Interpreter.o \
  InterpreterMessages.o \
  NumberCache.o \
  ProcessContext.o \
  ProcessingMode.o \
  Style.o \
  StyleEngine.o \
  primitive.o \
  style_inst.o
INCLUDE=-I$(srcdir)/../grove

GENSRCS=style_inst.cxx FlowObj_inst.cxx InterpreterMessages.h

FlowObj.o: FlowObj_inst.cxx
